```sql
SELECT 
    s.date,
    p.asin,
    p.program,
    p.period,
    d.distributor_view,
    SUM(s.total_ordered_units) AS total_ordered_units,
    SUM(s.ordered_revenue) AS ordered_revenue,
    AVG(s.average_selling_price) AS average_selling_price,
    SUM(t.glance_views) AS glance_views,
    AVG(t.conversion_rate) AS conversion_rate,
    SUM(i.shipped_units) AS shipped_units,
    SUM(i.shipped_revenue) AS shipped_revenue,
    AVG(i.average_net_ppm) AS average_net_ppm,
    AVG(i.average_procurable_product_oos) AS average_procurable_product_oos,
    SUM(i.total_on_hand_units) AS total_on_hand_units,
    SUM(i.total_on_hand_value) AS total_on_hand_value,
    SUM(nru.net_received_units) AS net_received_units,
    SUM(nru.net_received_value) AS net_received_value,
    SUM(opo.open_purchase_order_quantities) AS open_purchase_order_quantities,
    SUM(uoc.unfilled_customer_ordered_units) AS unfilled_customer_ordered_units,
    AVG(vcr.average_vendor_confirmation_rate) AS average_vendor_confirmation_rate,
    AVG(rfr.receive_fill