```sql
SELECT 
    DISTINCT EMBEDDING_MEDIUM_CODE_MEANING,
    STAINING_SUBSTANCE_CODE_MEANING,
    COUNT(*) AS OCCURRENCES
FROM 
    SM
WHERE 
    MODALITY = 'DICOM'
    AND SPECIMEN_PREPARATION_SEQUENCE IS NOT NULL
GROUP BY 
    EMBEDDING_MEDIUM_CODE_MEANING,
    STAINING_SUBSTANCE_CODE_MEANING;
```