```sql
WITH TCGA_BRCA AS (
    SELECT 
        CASE_ID,
        COPY_NUMBER_SEGMENT_START,
        COPY_NUMBER_SEGMENT_END,
        CYTOBAND_NAME,
        CYTOBAND_START,
        CYTOBAND_END
    FROM 
        gdc_archive
    WHERE 
        CASE_TYPE = 'BRCA' AND
        RELEASE_VERSION = 23
),
OVERLAP AS (
    SELECT 
        T1.CASE_ID,
        T1.CYTOBAND_NAME,
        T1.CYTOBAND_START,
        T1.CYTOBAND_END,
        T2.COPY_NUMBER_SEGMENT_START,
        T2.COPY_NUMBER_SEGMENT_END,
        SUM(CASE WHEN T2.COPY_NUMBER_SEGMENT_START BETWEEN T1.CYTOBAND_START AND T1.CYTOBAND_END THEN 1 ELSE 0 END) * 1.0 / (T1.CYTOBAND_END - T1.CYTOBAND_START + 1) AS OVERLAP_WEIGHTED_AVERAGE_COPY_NUMBER
    FROM 
        TCGA_BRCA T1
    INNER JOIN 
        gdc_archive T2 ON T1.CASE_ID = T2.CASE_ID