```sql
WITH AnnualAveragePurchasePrice AS (
    SELECT 
        YEAR,
        REGION,
        SUM(TOTAL_DOLLAR_AMOUNT) / SUM(TOTAL_QUANTITY_PURCHASED) AS AVG_PURCHASE_PRICE
    FROM 
        BITCOIN_TRANSACTIONS
    WHERE 
        YEAR > 1
    GROUP BY 
        YEAR, REGION
),
RankedRegions AS (
    SELECT 
        YEAR,
        REGION,
        AVG_PURCHASE_PRICE,
        RANK() OVER (PARTITION BY YEAR ORDER BY AVG_PURCHASE_PRICE DESC) AS PURCHASE_RANK
    FROM 
        AnnualAveragePurchasePrice
)
SELECT 
    YEAR,
    REGION,
    AVG_PURCHASE_PRICE,
    PURCHASE_RANK,
    CASE 
        WHEN LAG(AVG_PURCHASE_PRICE) OVER (PARTITION BY YEAR ORDER BY AVG_PURCHASE_PRICE DESC) IS NOT NULL THEN 
            ((AVG_PURCHASE_PRICE - LAG(AVG_PURCHASE_PRICE) OVER (PARTITION BY YEAR ORDER BY AVG_PURCHASE_PRICE DESC)) / LAG(AVG_PURCHASE_PRICE) OVER (PARTITION BY YEAR ORDER BY AVG_PURCHASE_PRICE DESC)) * 100
        ELSE 
            NULL
    END AS ANNUAL_PERCENTAGE_CHANGE
FROM 
    Ranked